"""Add status to job

Revision ID: 845ac55da830
Revises: 6be95e593e41
Create Date: 2026-01-18 17:35:26.209308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '845ac55da830'
down_revision: Union[str, Sequence[str], None] = '6be95e593e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('status', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('generation_error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'generation_error')
    op.drop_column('jobs', 'status')
    # ### end Alembic commands ###
