"""Add job platforms

Revision ID: eba72b686e8e
Revises: f1a2b3c4d5e6
Create Date: 2026-01-31 14:04:40.948040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eba72b686e8e'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('favicon_url', sa.String(), nullable=True),
    sa.Column('crawl_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('last_crawl_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_platforms_id'), 'job_platforms', ['id'], unique=False)
    op.create_index(op.f('ix_job_platforms_url'), 'job_platforms', ['url'], unique=False)
    op.create_index(op.f('ix_job_platforms_user_id'), 'job_platforms', ['user_id'], unique=False)
    op.add_column('jobs', sa.Column('platform_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'job_platforms', ['platform_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'platform_id')
    op.drop_index(op.f('ix_job_platforms_user_id'), table_name='job_platforms')
    op.drop_index(op.f('ix_job_platforms_url'), table_name='job_platforms')
    op.drop_index(op.f('ix_job_platforms_id'), table_name='job_platforms')
    op.drop_table('job_platforms')
    # ### end Alembic commands ###
