[supervisord]
nodaemon=true
user=root

[program:uvicorn]
command=uvicorn api:app --host 0.0.0.0 --port 80
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:celery]
command=celery -A worker.celery_app worker -B --loglevel=info --concurrency=4 -Q ai_queue
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
