[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[program:xvfb]
command=Xvfb :99 -screen 0 1920x1080x24 -nolisten tcp
priority=1
startsecs=2
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:uvicorn]
command=uvicorn main:app --host 0.0.0.0 --port 8080

[program:scraper_api]
command=uvicorn scraper_api:app --host 127.0.0.1 --port 8081
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:celery]
command=celery -A workers.worker.celery_app worker -B --loglevel=info --concurrency=4 -Q ai_queue --schedule database/celerybeat-schedule.db
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0


[program:scraper_celery]
command=celery -A workers.scraper_worker.celery_app worker --loglevel=info --concurrency=2 -Q scraper_queue
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
