[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[program:uvicorn]
command=uvicorn api:app --host 0.0.0.0 --port 8080
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:celery]
command=celery -A worker.celery_app worker -B --loglevel=info --concurrency=4 -Q ai_queue --schedule database/celerybeat-schedule.db
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0


[program:scraper_celery]
command=celery -A scraper_worker.celery_app worker --loglevel=info --concurrency=2 -Q scraper_queue
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
