"""add url to jobs

Revision ID: 0ad94af91f06
Revises: 5ee5a5c23e97
Create Date: 2026-01-18 12:28:46.008265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ad94af91f06'
down_revision: Union[str, Sequence[str], None] = '5ee5a5c23e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'url')
    # ### end Alembic commands ###
