"""add job_urls to user_settings

Revision ID: 6be95e593e41
Revises: 0ad94af91f06
Create Date: 2026-01-18 13:33:21.596087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6be95e593e41'
down_revision: Union[str, Sequence[str], None] = '0ad94af91f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('job_urls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'job_urls')
    # ### end Alembic commands ###
