"""add_notification_fields

Revision ID: e33149c31cdc
Revises: eba72b686e8e
Create Date: 2026-01-31 17:05:44.154475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e33149c31cdc'
down_revision: Union[str, Sequence[str], None] = 'eba72b686e8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_platforms', sa.Column('is_notification_enabled', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('notification_sent', sa.Boolean(), nullable=True))
    op.add_column('user_settings', sa.Column('gmail_address', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('gmail_app_password', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('pushover_user_key', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('pushover_api_token', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('active_notification_service', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'active_notification_service')
    op.drop_column('user_settings', 'pushover_api_token')
    op.drop_column('user_settings', 'pushover_user_key')
    op.drop_column('user_settings', 'gmail_app_password')
    op.drop_column('user_settings', 'gmail_address')
    op.drop_column('jobs', 'notification_sent')
    op.drop_column('job_platforms', 'is_notification_enabled')
    # ### end Alembic commands ###
