
export type Language = 'en' | 'de';

export const translations = {
    en: {
        // Navigation
        dashboard: "Dashboard",
        settings: "Settings",
        adminUsers: "Admin Users",
        applications: "Applications",

        // Dashboard Shell
        collapseSidebar: "Collapse Sidebar",
        expandSidebar: "Expand Sidebar",
        jobAgent: "JobAgent",
        deepIntelligence: "Deep Intelligence",

        // User Menu
        signOut: "Sign Out",
        profile: "Profile",
        help: "Help",
        showTutorial: "Show Tutorial",
        signedInAs: "Signed in as",
        member: "Member",
        admin: "Admin",
        adminArea: "Admin Area",

        // Theme Toggler
        switchLight: "Switch to Light Mode",
        switchDark: "Switch to Dark Mode",

        // Language Toggler
        switchLanguage: "Change Language",
        german: "German",
        english: "English",

        // Home Page
        jobIntelligence: "Job Intelligence",
        opportunitiesDetected: "Opportunities detected",
        searchPlaceholder: "Analyze new job platform...",
        scan: "SCAN",
        systemWaiting: "System waiting for input.",
        sortBy: "Sort by:",
        relevance: "Relevance",
        newest: "Newest",
        analysis: "Analysis",
        applySource: "Apply Source",
        generateApplication: "Generate Application",
        viewApplication: "View Application",
        failedRetry: "Failed - Retry",
        processing: "Processing...",
        removeFromFavorites: "Remove from favorites",
        addToFavorites: "Add to favorites",
        deleteJob: "Delete job",
        viewDetails: "View Details",
        closeDetails: "Close Details",
        match: "match",
        deleteConfirm: "Are you sure you want to delete this job?",
        statusApplied: "Applied",
        statusInterview: "Interview",
        statusOffer: "Offer",
        statusRejected: "Rejected",
        statusAccepted: "Accepted",
        statusOpen: "Open",
        statusDrafted: "Drafted",
        updateStatus: "Update Status",
        applicationManagement: "Application Management",

        // Crawl Status
        jobSearch: "Job Search",
        searchingForJobs: "Searching for jobs...",
        jobsFound: "Jobs found",
        processingJobDetails: "{count} of {total} job details processed",
        loadJobDetails: "Load job details",
        extractingDescriptions: "Extracting job descriptions...",
        analyzingCount: "{count} of {total} jobs analyzed",
        allJobsAnalyzed: "All jobs successfully analyzed!",
        jobsRatedAndSaved: "{count} {jobs} rated and saved.",
        job: "job",
        jobs: "jobs",
        cancelCrawl: "Cancel crawl",
        cancelCrawlConfirm: "Are you sure you want to cancel this crawl job?",

        // Application Modal
        applicationPreview: "Application Preview",
        close: "Close",
        copyText: "Copy Text",
        saveAsPdf: "Save as PDF",
        copiedToClipboard: "Copied to clipboard!",
        downloadFailed: "Download failed",
        pdfDownloadError: "Error during PDF download.",

        // Login
        systemAccess: "System Access",
        identity: "Username",
        secureKey: "Password",
        initializeSession: "Login",
        authFailed: "Authentication failed.",
        systemUnreachable: "System unreachable.",

        // Settings
        profileConfiguration: "Profile Configuration",
        profileSubtitle: "Manage your professional identity and search preferences",
        saveChanges: "Save Changes",
        tryAgain: "Try Again",
        notifications: "Notifications",
        saving: "Saving...",
        saved: "Saved! ✅",
        error: "Error ❌",
        success: "Success ✅",
        analyzingPdf: "Analyzing PDF... (takes 10-20s)",
        uploadFailed: "Upload failed",
        importSuccess: "CV imported successfully! 🎉",
        importFailed: "Import failed ❌",
        targetParameters: "Target Parameters",
        targetRole: "Target Role",
        skillsComma: "Skills (Comma sep.)",
        minSalary: "Min Salary",
        location: "Location",
        preferencesNatural: "Preferences (Natural Language)",
        experience: "Experience",
        keyProjects: "Key Projects",
        education: "Education",
        uploadCv: "Upload CV",
        dropPdf: "Drop your PDF to auto-extract skills and experience.",
        selectPdf: "Select PDF",
        analyzing: "Analyzing...",
        security: "Security",
        dangerZone: "Danger Zone",
        deleteAllJobs: "Delete All Jobs",
        deleteProfileOnly: "Delete Profile Only",
        factoryReset: "Factory Reset (All Data)",
        deleteJobsConfirm: "Are you sure? This will delete all your crawled jobs permanently.",
        deleteProfileConfirm: "Are you sure? This will delete your profile and CV data permanently.",
        factoryResetConfirm: "⚠️ WARNING: This will delete ALL jobs and your entire profile. Everything. Sure?",
        loadingProfile: "Loading Profile...",
        startingCrawler: "Starting Crawler...",
        crawlJobsDispatched: "Crawl jobs dispatched! 🕵️‍♂️",
        loading: "Loading...",
        dayUnit: "d",
        hourUnit: "h",
        minUnit: "m",
        now: "now",

        // Experience & Projects Fields
        company: "Company",
        role: "Role",
        duration: "Duration",
        description: "Description",
        projectName: "Project Name",
        techStack: "Tech Stack",

        // Admin
        userManagement: "User Management",
        adminControlPanel: "Admin Control Panel",
        createNewUser: "Create New User",
        username: "Username",
        password: "Password",
        createUser: "Create User",
        id: "ID",
        clearance: "Clearance",
        actions: "Actions",
        delete: "Delete",
        areYouCertain: "Are you certain?",
        errorCreatingUser: "Error creating user",
        verifyingClearance: "Verifying Clearance...",

        // Password Change
        currentPassword: "Current Password",
        newPassword: "New Password",
        updatePassword: "Update Password",
        updating: "Updating...",
        passwordUpdated: "Password updated! ✅",
        networkError: "Network Error",

        // Tutorial
        tutorialWelcomeTitle: "Welcome to AI JobAgent! 🚀",
        tutorialWelcomeDesc: "Your personal assistant for automated job searching. Let us show you how to get the best out of the app.",
        tutorialNavTitle: "Navigation 🧭",
        tutorialNavDesc: "Here you can find the dashboard, your settings, and the admin area.",
        tutorialAnalysisTitle: "Market Analysis ⚡",
        tutorialAnalysisDesc: "Enter a keyword here to start a targeted real-time analysis of the market. The AI finds matching jobs immediately.",
        tutorialSortTitle: "Sorting 📊",
        tutorialSortDesc: "Sort the results by relevance (AI score) or by the publication date.",
        tutorialResultsTitle: "Intelligent Results 💡",
        tutorialResultsDesc: "Every job is analyzed. The score shows you how well the position matches your profile.",
        tutorialAppsTitle: "Manage Applications 📁",
        tutorialAppsDesc: "Track your progress here. You can update the status of each job from 'Applied' to 'Interview' or 'Accepted'.",
        stepOf: "STEP {n} OF {m}",
        back: "Back",
        skip: "Skip",
        next: "Next",
        start: "Start",

        // Job Platforms
        jobPlatforms: "Job Platforms",
        platformsSubtitle: "Manage URLs and automated scan intervals",
        adding: "Adding...",
        platformAdded: "Platform added! ✅",
        crawlInProgress: "Crawl in progress...",
        scanNow: "Scan now",
        remove: "Remove",
        everyHour: "Every Hour",
        every6Hours: "Every 6 Hours",
        every12Hours: "Every 12 Hours",
        every24Hours: "Every 24 Hours",
        everyWeek: "Every Week",
        neverScanned: "Never scanned",
        lastScan: "Last Scan",
        lastScanned: "Last: {date}",
        addPlatformPlaceholder: "Add new platform URL (e.g. LinkedIn, Indeed...)",
        invalidUrl: "Invalid URL format",
        invalidUrlProtocol: "URL must start with http:// or https://",
        notificationsEnabled: "Notifications Enabled",
        notificationsDisabled: "Notifications Disabled",
        platformActive: "Platform active",
        platformInactive: "Platform inactive",
        deactivated: "Deactivated",

        // Filters
        all: "All",
        favorites: "Favorites",
        noFavorites: "No Favorites",
        confirm: "Confirm",
        cancel: "Cancel",

        // Missing keys from reports
        removePlatform: "Remove platform",
        userCreated: "User created! ✅",
        deleteUser: "Delete User",

        // Dynamic List
        addItem: "Add Item",
        noEntries: "No entries yet.",
        removeEntry: "Remove entry",
        completeProfileFirst: "Please complete your profile first."
    },
    de: {
        // Navigation
        dashboard: "Dashboard",
        settings: "Einstellungen",
        adminUsers: "Admin Benutzer",
        applications: "Bewerbungen",

        // Dashboard Shell
        collapseSidebar: "Sidebar einklappen",
        expandSidebar: "Sidebar ausklappen",
        jobAgent: "JobAgent",
        deepIntelligence: "Tiefe Intelligenz",

        // User Menu
        signOut: "Abmelden",
        profile: "Profil",
        help: "Hilfe",
        showTutorial: "Tutorial anzeigen",
        signedInAs: "Angemeldet als",
        member: "Mitglied",
        admin: "Administrator",
        adminArea: "Admin-Bereich",

        // Theme Toggler
        switchLight: "In den hellen Modus wechseln",
        switchDark: "In den dunklen Modus wechseln",

        // Language Toggler
        switchLanguage: "Sprache ändern",
        german: "Deutsch",
        english: "Englisch",

        // Home Page
        jobIntelligence: "Job Intelligence",
        opportunitiesDetected: "Gefundene Stellenanzeigen",
        searchPlaceholder: "Neue Jobplattform analysieren...",
        scan: "SCAN",
        systemWaiting: "System wartet auf Eingabe.",
        sortBy: "Sortieren nach:",
        relevance: "Relevanz",
        newest: "Neueste",
        analysis: "Analyse",
        applySource: "Original-Anzeige",
        generateApplication: "Bewerbung erstellen",
        viewApplication: "Bewerbung ansehen",
        failedRetry: "Fehlgeschlagen - Erneut versuchen",
        processing: "Wird verarbeitet...",
        removeFromFavorites: "Von Favoriten entfernen",
        addToFavorites: "Zu Favoriten hinzufügen",
        deleteJob: "Job löschen",
        viewDetails: "Details ansehen",
        closeDetails: "Details schließen",
        match: "match",
        deleteConfirm: "Möchten Sie diesen Job wirklich löschen?",
        statusApplied: "Beworben",
        statusInterview: "Interview",
        statusOffer: "Angebot",
        statusRejected: "Abgelehnt",
        statusAccepted: "Angenommen",
        statusOpen: "Offen",
        statusDrafted: "Entwurf",
        updateStatus: "Status ändern",
        applicationManagement: "Bewerbungs-Management",

        // Crawl Status
        jobSearch: "Job-Suche",
        searchingForJobs: "Suche nach Jobs...",
        jobsFound: "Jobs gefunden",
        processingJobDetails: "{count} von {total} Job Details werden verarbeitet",
        loadJobDetails: "Job Details laden",
        extractingDescriptions: "Extrahiere Stellenbeschreibungen...",
        analyzingCount: "{count} von {total} Jobs analysiert",
        allJobsAnalyzed: "Alle Jobs erfolgreich analysiert!",
        jobsRatedAndSaved: "{count} {jobs} wurden bewertet und gespeichert.",
        job: "Job wurde",
        jobs: "Jobs wurden",
        cancelCrawl: "Crawl abbrechen",
        cancelCrawlConfirm: "Möchten Sie diesen Crawl-Job wirklich abbrechen?",

        // Application Modal
        applicationPreview: "Anschreiben Vorschau",
        close: "Schließen",
        copyText: "Text kopieren",
        saveAsPdf: "Als PDF speichern",
        copiedToClipboard: "In die Zwischenablage kopiert!",
        downloadFailed: "Download fehlgeschlagen",
        pdfDownloadError: "Fehler beim PDF Download.",

        // Login
        systemAccess: "System-Zugang",
        identity: "Benutzername",
        secureKey: "Passwort",
        initializeSession: "Login",
        authFailed: "Authentifizierung fehlgeschlagen.",
        systemUnreachable: "System nicht erreichbar.",

        // Settings
        profileConfiguration: "Profil-Konfiguration",
        profileSubtitle: "Verwalte deine berufliche Identität und Sucheinstellungen",
        saveChanges: "Änderungen speichern",
        tryAgain: "Erneut versuchen",
        notifications: "Benachrichtigungen",
        saving: "Speichert...",
        saved: "Gespeichert! ✅",
        error: "Fehler ❌",
        success: "Erfolg ✅",
        analyzingPdf: "Analysiere PDF... (dauert 10-20s)",
        uploadFailed: "Upload fehlgeschlagen",
        importSuccess: "CV erfolgreich importiert! 🎉",
        importFailed: "Import fehlgeschlagen ❌",
        targetParameters: "Ziel-Parameter",
        targetRole: "Ziel-Rolle",
        skillsComma: "Skills (Komma-getrennt)",
        minSalary: "Mindestgehalt",
        location: "Standort",
        preferencesNatural: "Präferenzen (Natürliche Sprache)",
        experience: "Erfahrung",
        keyProjects: "Wichtige Projekte",
        education: "Ausbildung",
        uploadCv: "Lebenslauf hochladen",
        dropPdf: "PDF ablegen, um Skills und Erfahrung automatisch zu extrahieren.",
        selectPdf: "PDF auswählen",
        analyzing: "Analysiere...",
        security: "Sicherheit",
        dangerZone: "Gefahrenzone",
        deleteAllJobs: "Alle Jobs löschen",
        deleteProfileOnly: "Nur Profil löschen",
        factoryReset: "Werkseinstellung (Alle Daten)",
        deleteJobsConfirm: "Sicher? Dies wird alle deine gecrawlten Jobs dauerhaft löschen.",
        deleteProfileConfirm: "Sicher? Dies wird dein Profil und deine CV-Daten dauerhaft löschen.",
        factoryResetConfirm: "⚠️ WARNUNG: Dies wird ALLE Jobs und dein gesamtes Profil löschen. Alles. Sicher?",
        loadingProfile: "Profil wird geladen...",
        startingCrawler: "Crawler wird gestartet...",
        crawlJobsDispatched: "Crawl-Jobs versandt! 🕵️‍♂️",
        loading: "Wird geladen...",
        dayUnit: "T",
        hourUnit: "Std",
        minUnit: "Min",
        now: "jetzt",

        // Experience & Projects Fields
        company: "Firma",
        role: "Rolle",
        duration: "Zeitraum",
        description: "Beschreibung",
        projectName: "Projektname",
        techStack: "Tech Stack",

        // Admin
        userManagement: "Benutzerverwaltung",
        adminControlPanel: "Admin-Kontrollzentrum",
        createNewUser: "Neuen Benutzer erstellen",
        username: "Benutzername",
        password: "Passwort",
        createUser: "Benutzer erstellen",
        id: "ID",
        clearance: "Freigabe",
        actions: "Aktionen",
        delete: "Löschen",
        areYouCertain: "Bist du sicher?",
        errorCreatingUser: "Fehler beim Erstellen des Benutzers",
        verifyingClearance: "Prüfe Berechtigung...",

        // Password Change
        currentPassword: "Aktuelles Passwort",
        newPassword: "Neues Passwort",
        updatePassword: "Passwort aktualisieren",
        updating: "Aktualisiere...",
        passwordUpdated: "Passwort aktualisiert! ✅",
        networkError: "Netzwerkfehler",

        // Tutorial
        tutorialWelcomeTitle: "Willkommen beim AI JobAgent! 🚀",
        tutorialWelcomeDesc: "Dein persönlicher Assistent für die automatisierte Jobsuche. Lass uns dir zeigen, wie du das Beste aus der App herausholst.",
        tutorialNavTitle: "Navigation 🧭",
        tutorialNavDesc: "Hier findest du das Dashboard, deine Einstellungen und den Admin-Bereich.",
        tutorialAnalysisTitle: "Markt-Analyse ⚡",
        tutorialAnalysisDesc: "Gib hier ein Keyword ein, um eine gezielte Echtzeit-Analyse des Marktes zu starten. Die KI findet passende Stellen sofort.",
        tutorialSortTitle: "Sortierung 📊",
        tutorialSortDesc: "Sortiere die Ergebnisse nach Relevanz (KI-Score) oder nach dem Datum der Veröffentlichung.",
        tutorialResultsTitle: "Intelligente Ergebnisse 💡",
        tutorialResultsDesc: "Jeder Job wird analysiert. Der Score zeigt dir, wie gut die Stelle zu deinem Profil passt.",
        tutorialAppsTitle: "Bewerbungen verwalten 📁",
        tutorialAppsDesc: "Verfolge hier deinen Fortschritt. Du kannst den Status jeder Bewerbung von 'Beworben' bis 'Angenommen' aktualisieren.",
        stepOf: "SCHRITT {n} VON {m}",
        back: "Zurück",
        skip: "Überspringen",
        next: "Weiter",
        start: "Starten",

        // Job Platforms
        jobPlatforms: "Job-Plattformen",
        platformsSubtitle: "URLs und automatisierte Scan-Intervalle verwalten",
        adding: "Füge hinzu...",
        platformAdded: "Plattform hinzugefügt! ✅",
        crawlInProgress: "Crawl läuft...",
        scanNow: "Jetzt scannen",
        remove: "Entfernen",
        everyHour: "Jede Stunde",
        every6Hours: "Alle 6 Stunden",
        every12Hours: "Alle 12 Stunden",
        every24Hours: "Alle 24 Stunden",
        everyWeek: "Jede Woche",
        neverScanned: "Noch nie gescannt",
        lastScan: "Letzter Scan",
        lastScanned: "Zuletzt: {date}",
        addPlatformPlaceholder: "Neue Plattform-URL hinzufügen (z.B. LinkedIn, Indeed...)",
        invalidUrl: "Ungültiges URL-Format",
        invalidUrlProtocol: "URL muss mit http:// oder https:// beginnen",
        notificationsEnabled: "Benachrichtigungen aktiviert",
        notificationsDisabled: "Benachrichtigungen deaktiviert",
        platformActive: "Plattform aktiv",
        platformInactive: "Plattform inaktiv",
        deactivated: "Deaktiviert",

        // Filters
        all: "Alle",
        favorites: "Favoriten",
        noFavorites: "Keine Favoriten",
        confirm: "Bestätigen",
        cancel: "Abbrechen",

        // Missing keys from reports
        removePlatform: "Plattform entfernen",
        userCreated: "Benutzer erstellt! ✅",
        deleteUser: "Benutzer löschen",

        // Dynamic List
        addItem: "Eintrag hinzufügen",
        noEntries: "Noch keine Einträge.",
        removeEntry: "Eintrag entfernen",
        completeProfileFirst: "Bitte vervollständige zuerst dein Profil."
    }
};

export type TranslationKey = keyof typeof translations.en;
