
export type Language = 'en' | 'de';

export const translations = {
    en: {
        // Navigation
        dashboard: "Dashboard",
        listings: "Listings",
        statistics: "Statistics",
        scheduledPlatforms: "Scheduled Platforms",
        settings: "Settings",
        account: "Account",
        userManagement: "User Management",
        applications: "Applications",

        // Dashboard Shell
        collapseSidebar: "Collapse Sidebar",
        expandSidebar: "Expand Sidebar",
        jobAgent: "JobAgent",
        deepIntelligence: "Deep Intelligence",
        more: "More",

        // User Menu
        signOut: "Sign Out",
        profile: "Profile",
        help: "Help",
        signedInAs: "Signed in as",
        member: "Member",
        admin: "Admin",
        adminArea: "Admin Area",

        // Theme Toggler
        switchLight: "Switch to Light Mode",
        switchDark: "Switch to Dark Mode",

        // Language Toggler
        switchLanguage: "Change Language",
        german: "German",
        english: "English",

        // Home Page
        jobIntelligence: "Job Intelligence",
        opportunitiesDetected: "Opportunities detected",
        searchPlaceholder: "Import job by URL...",
        scan: "IMPORT",
        systemWaiting: "System waiting for input.",
        sortBy: "Sort by:",
        relevance: "Relevance",
        newest: "Newest",
        analysis: "Analysis",
        applySource: "Apply Source",
        generateApplication: "Generate Application",
        viewApplication: "View Application",
        failedRetry: "Failed - Retry",
        processing: "Processing...",
        removeFromFavorites: "Remove from favorites",
        addToFavorites: "Add to favorites",
        deleteJob: "Delete job",
        viewDetails: "View Details",
        closeDetails: "Close Details",
        edit: "Edit",
        match: "match",
        deleteConfirm: "Are you sure you want to delete this job?",
        statusApplied: "Applied",
        statusInterview: "Interview",
        statusOffer: "Offer",
        statusRejected: "Rejected",
        statusAccepted: "Accepted",
        statusOpen: "Open",
        statusDrafted: "Drafted",
        updateStatus: "Update Status",
        applicationManagement: "Application Management",
        applicationPipeline: "Application Pipeline",
        otherStatus: "Other:",

        // Crawl Status
        jobSearch: "Job Search",
        searchingForJobs: "Searching for jobs...",
        jobsFound: "Jobs found",
        jobsSaved: "saved",
        jobsSkipped: "skipped",
        processingJobDetails: "{count} of {total} job details processed",
        loadJobDetails: "Load job details",
        extractingDescriptions: "Extracting job descriptions...",
        aiExtraction: "AI Extraction",
        aiExtractionCount: "{count} of {total} extracted",
        analyzingCount: "{count} of {total} jobs analyzed",
        allJobsAnalyzed: "All jobs successfully analyzed!",
        jobsRatedAndSaved: "{count} {jobs} rated and saved.",
        job: "job",
        jobs: "jobs",
        cancelCrawl: "Cancel crawl",
        cancelCrawlConfirm: "Are you sure you want to cancel this crawl job?",

        // Application Modal
        applicationPreview: "Application Preview",
        close: "Close",
        copyText: "Copy Text",
        saveAsPdf: "Save as PDF",
        copiedToClipboard: "Copied to clipboard!",
        downloadFailed: "Download failed",
        pdfDownloadError: "Error during PDF download.",

        // Login
        systemAccess: "System Access",
        identity: "Username",
        secureKey: "Password",
        initializeSession: "Login",
        authFailed: "Authentication failed.",
        systemUnreachable: "System unreachable.",

        // Settings
        profileConfiguration: "Profile Configuration",
        profileSubtitle: "Manage your professional identity and search preferences",
        saveChanges: "Save Changes",
        tryAgain: "Try Again",
        notifications: "Notifications",
        generating: "Generating...",
        updated: "Updated!",
        saving: "Saving...",
        saved: "Saved!",
        error: "Error",
        success: "Success",
        analyzingPdf: "Analyzing PDF... (takes 10-20s)",
        uploadFailed: "Upload failed",
        importSuccess: "CV imported successfully!",
        importFailed: "Import failed",
        targetParameters: "Target Parameters",
        targetRole: "Target Role",
        skillsComma: "Skills (Comma sep.)",
        minSalary: "Min Salary",
        location: "Location",
        preferencesNatural: "Preferences (Natural Language)",
        experience: "Experience",
        keyProjects: "Key Projects",
        education: "Education",
        uploadCv: "Upload CV",
        dropPdf: "Drop your PDF to auto-extract skills and experience.",
        selectPdf: "Select PDF",
        analyzing: "Analyzing...",
        security: "Security",
        dangerZone: "Danger Zone",
        deleteAllJobs: "Delete All Jobs",
        deleteProfileOnly: "Delete Profile Only",
        factoryReset: "Factory Reset (All Data)",
        deleteJobsConfirm: "Are you sure? This will delete all your crawled jobs permanently.",
        deleteProfileConfirm: "Are you sure? This will delete your profile and CV data permanently.",
        factoryResetConfirm: "WARNING: This will delete ALL jobs and your entire profile. Everything. Sure?",
        loadingProfile: "Loading Profile...",
        startingCrawler: "Starting Crawler...",
        crawlJobsDispatched: "Crawl jobs dispatched!",
        loading: "Loading...",
        dayUnit: "d",
        hourUnit: "h",
        minUnit: "m",
        now: "now",

        // Experience & Projects Fields
        company: "Company",
        role: "Role",
        duration: "Duration",
        description: "Description",
        projectName: "Project Name",
        techStack: "Tech Stack",

        // Admin
        adminControlPanel: "Admin Control Panel",
        createNewUser: "Create New User",
        username: "Username",
        password: "Password",
        createUser: "Create User",
        id: "ID",
        clearance: "Clearance",
        actions: "Actions",
        delete: "Delete",
        areYouCertain: "Are you certain?",
        errorCreatingUser: "Error creating user",
        verifyingClearance: "Verifying Clearance...",

        // Password Change
        currentPassword: "Current Password",
        newPassword: "New Password",
        updatePassword: "Update Password",
        updating: "Updating...",
        passwordUpdated: "Password updated!",
        networkError: "Network Error",

        // Job Platforms
        jobPlatforms: "Job Platforms",
        platformsSubtitle: "Manage URLs and automated scan intervals",
        notificationsSubtitle: "Configure your notification adapters",
        adding: "Adding...",
        platformAdded: "Platform added!",
        crawlInProgress: "Crawl in progress...",
        scanNow: "Scan now",
        remove: "Remove",
        everyHour: "Every Hour",
        every6Hours: "Every 6 Hours",
        every12Hours: "Every 12 Hours",
        every24Hours: "Every 24 Hours",
        everyWeek: "Every Week",
        neverScanned: "Never scanned",
        lastScan: "Last Scan",
        lastScanned: "Last: {date}",
        addPlatformPlaceholder: "Add new platform URL (e.g. LinkedIn, Indeed...)",
        invalidUrl: "Invalid URL format",
        invalidUrlProtocol: "URL must start with http:// or https://",
        notificationsEnabled: "Notifications Enabled",
        notificationsDisabled: "Notifications Disabled",
        platformActive: "Platform active",
        platformInactive: "Platform inactive",
        deactivated: "Deactivated",

        // Filters
        all: "All",
        favorites: "Favorites",
        noFavorites: "No Favorites",
        confirm: "Confirm",
        cancel: "Cancel",

        // Missing keys from reports
        removePlatform: "Remove platform",
        userCreated: "User created!",
        deleteUser: "Delete User",

        // Dynamic List
        addItem: "Add Item",
        noEntries: "No entries yet.",
        removeEntry: "Remove entry",
        completeProfileFirst: "Please complete your profile first.",

        // Job list filters
        filterSearchPlaceholder: "Search by title or company...",
        allDomains: "All domains",
        allPlatforms: "All platforms",
        allStatuses: "All statuses",
        withApplication: "With cover letter",
        clearAllFilters: "Clear all filters",

        // Deletion actions
        alsoDeleteListings: "Also delete all associated listings",
        deleteAllFromPlatform: "Delete all from this platform",
        keepFavorites: "Keep favorites",
        keepApplications: "Keep listings with application",
        select: "Select",
        selected: "Selected",
        selectAllVisible: "Select all visible",
        bulkDelete: "Delete Selected",
        deleteAllFromCompany: "Delete all from {company}",

        // Needs Attention / Follow-up / Prep
        needsAttention: "Needs Attention",
        prepMaterialAvailable: "Prep Material",
        followUpDue: "Follow-up due",

        // Job Details Modal
        overview: "Overview",
        application: "Application",
        interviewPrep: "Interview Prep",
        companyProfile: "Company",
        historyTab: "History",
        noApplication: "No application generated yet",
        jobDescription: "Show job description",

        // Tab Labels
        status: "Status",
        documents: "Documents",
        shortInfo: "Info",
        shortApp: "App",
        shortInt: "Int",
        shortCo: "Co",
        shortStatus: "Status",
        shortDocs: "Docs",

        // Setup Warnings
        setupRequired: "Setup Required",
        profileIncomplete: "Profile Incomplete",
        noNotificationAdapter: "No Notifications",
        completeProfileDesc: "Your profile is not fully filled out. Complete it to get better job matches.",
        noNotificationAdapterDesc: "You haven't configured any notification services. You won't be notified about new jobs.",
        actionCompleteProfile: "Complete Profile",
        actionConfigureNotifications: "Configure Notifications",
        found: "found",
        new: "new",

        // Companies
        companies: "Companies",
        companiesPageTitle: "Company Profiles",
        companiesPageSubtitle: "Deep intelligence on all companies in your pipeline",

        // Language Preference
        languagePreference: "Language Preference",

        // Profile Page
        profileAndResume: "Profile & Resume",
        profileCompletion: "Profile Completion",
        targetJob: "Target Job",
        resume: "Resume",
        universityPlaceholder: "University, Degree...",

        // Settings - Notification Adapters
        deliveryMethods: "Delivery Methods",
        notificationAdapterInfo: "Configure your notification credentials here. Activating platforms is done individually on the dashboard.",
        active: "Active",
        inactive: "Inactive",
        importantSecurityNote: "Important Security Note",
        gmailAppPasswordNote: "Use exclusively an App Password. Your regular Google password will be rejected for security reasons.",
        createAppPassword: "Create App Password",
        emailAddress: "Email Address",
        appPassword: "App Password",
        emailService: "Email Service",
        pushNotifications: "Push Notifications",
        pushoverKeysInfo: "Get your keys at Pushover.net",
        userKey: "User Key",
        apiToken: "API Token",
        notificationTemplates: "Notification Templates",
        customTemplates: "Custom Templates",

        // Archive
        archiveJob: "Archive job",
        archiveConfirm: "Are you sure you want to archive this job?",
        archiveSelected: "Archive Selected",
        archiveAllFromCompany: "Archive all from {company}",
        archiveEmpty: "No archived jobs.",
        archivePageTitle: "Archive",
        archivePageSubtitle: "Jobs archived from your listings",

        // JobDocumentsTab
        notes: "Notes",
        personalNotesPlaceholder: "Job notes, interview notes, personal impressions...",
        savingNotes: "Saving...",
        notesSaved: "Saved",
        tasks: "Tasks",
        noTasks: "No tasks - add one.",
        newTask: "New task...",
        files: "Files",
        fileLimitInfo: "PDF, DOCX, Image - max. 10 MB",
        uploading: "Uploading...",
        dropFileHere: "Drop file here or click",
        loadingFile: "Loading...",
        clickToOpen: "Click to open",
        noFiles: "No files uploaded yet",
        viewFile: "View",
        downloadFile: "Download",
        maxFileSize: "Max. file size 10 MB",
        uploadFailed: "Upload failed",
        genericError: "An error occurred",

        // Guidance
        guidanceWhatNow: "What now?",
        guidanceOpenNext: "Check the job and decide if you want to apply.",
        guidanceOpenItem1: "Read AI analysis (Overview tab)",
        guidanceOpenItem2: "Read job description completely",
        guidanceOpenItem3: "Short research on the company",
        guidanceOpenItem4: "Start application draft",
        guidanceOpenNudge: "Every process starts with an honest self-assessment.",
        
        guidanceDraftedNext: "Review your application draft and send it.",
        guidanceDraftedItem1: "Application draft generated",
        guidanceDraftedItem2: "Check draft for completeness and tone",
        guidanceDraftedItem3: "Personalize cover letter (name, job reference)",
        guidanceDraftedItem4: "Send documents / fill out form",
        guidanceDraftedNudge: "Perfect is the enemy of good — send it now.",

        guidanceAppliedNext: "Document your application and plan your follow-up.",
        guidanceAppliedItem1: "Received or checked application confirmation",
        guidanceAppliedItem2: "Follow-up date set",
        guidanceAppliedItem3: "Interview prep prepared",
        guidanceAppliedItem4: "Patience: feedback time is often 2–4 weeks",
        guidanceAppliedNudge: "You applied — that was the hardest step.",

        guidanceInterviewNext: "Prepare intensively for the interview.",
        guidanceInterviewItem1: "Interview prep material generated",
        guidanceInterviewItem2: "3 own strength examples (STAR method) prepared",
        guidanceInterviewItem3: "Questions for the company prepared",
        guidanceInterviewItem4: "Logistics cleared (location, time, contact, video link)",
        guidanceInterviewNudge: "Preparation is the difference between luck and skill.",

        guidanceOfferNext: "Analyze the offer carefully before you respond.",
        guidanceOfferItem1: "Check conditions (salary, vacation, remote share)",
        guidanceOfferItem2: "Compared salary benchmark",
        guidanceOfferItem3: "Identified negotiation room",
        guidanceOfferItem4: "Take 48h to think (professional & common)",
        guidanceOfferNudge: "An offer is an invitation to talk, not an ultimatum.",

        guidanceAcceptedNext: "Congratulations! Prepare your start.",
        guidanceAcceptedItem1: "Written contract received and checked",
        guidanceAcceptedItem2: "Confirmed start date and onboarding info",
        guidanceAcceptedItem3: "Politely declined all other applications",
        guidanceAcceptedItem4: "Archived open positions here",
        guidanceAcceptedNudge: "You did it. Now the next chapter begins.",

        guidanceRejectedNext: "Get feedback and draw learning from the process.",
        guidanceRejectedItem1: "Read rejection letter carefully",
        guidanceRejectedItem2: "Request feedback (for personal contacts)",
        guidanceRejectedItem3: "Adjusted application documents for next round",
        guidanceRejectedItem4: "Identify next suitable position",
        guidanceRejectedNudge: "A rejection shows you which door fits better.",

        guidanceFailedNext: "Check if there is a technical problem and start again.",
        guidanceFailedItem1: "Read error message in overview",
        guidanceFailedItem2: "Check application draft manually",
        guidanceFailedItem3: "Tried to regenerate",
        guidanceFailedItem4: "Contact support if problem persists",
        guidanceFailedNudge: "Sometimes it hooks technically — no setback, but a hint.",
    },
    de: {
        // Navigation
        dashboard: "Dashboard",
        listings: "Listings",
        statistics: "Statistiken",
        scheduledPlatforms: "Geplante Plattformen",
        settings: "Einstellungen",
        account: "Konto",
        userManagement: "Benutzerverwaltung",
        applications: "Bewerbungen",

        // Dashboard Shell
        collapseSidebar: "Sidebar einklappen",
        expandSidebar: "Sidebar ausklappen",
        jobAgent: "JobAgent",
        deepIntelligence: "Tiefe Intelligenz",
        more: "Mehr",

        // User Menu
        signOut: "Abmelden",
        profile: "Profil",
        help: "Hilfe",
        signedInAs: "Angemeldet als",
        member: "Mitglied",
        admin: "Administrator",
        adminArea: "Admin-Bereich",

        // Theme Toggler
        switchLight: "In den hellen Modus wechseln",
        switchDark: "In den dunklen Modus wechseln",

        // Language Toggler
        switchLanguage: "Sprache ändern",
        german: "Deutsch",
        english: "Englisch",

        // Home Page
        jobIntelligence: "Job Intelligence",
        opportunitiesDetected: "Gefundene Stellenanzeigen",
        searchPlaceholder: "Job per URL importieren...",
        scan: "IMPORT",
        systemWaiting: "System wartet auf Eingabe.",
        sortBy: "Sortieren nach:",
        relevance: "Relevanz",
        newest: "Neueste",
        analysis: "Analyse",
        applySource: "Original-Anzeige",
        generateApplication: "Bewerbung erstellen",
        viewApplication: "Bewerbung ansehen",
        failedRetry: "Fehlgeschlagen - Erneut versuchen",
        processing: "Wird verarbeitet...",
        removeFromFavorites: "Von Favoriten entfernen",
        addToFavorites: "Zu Favoriten hinzufügen",
        deleteJob: "Job löschen",
        viewDetails: "Details ansehen",
        closeDetails: "Details schließen",
        edit: "Bearbeiten",
        match: "match",
        deleteConfirm: "Möchten Sie diesen Job wirklich löschen?",
        statusApplied: "Beworben",
        statusInterview: "Interview",
        statusOffer: "Angebot",
        statusRejected: "Abgelehnt",
        statusAccepted: "Angenommen",
        statusOpen: "Offen",
        statusDrafted: "Entwurf",
        updateStatus: "Status ändern",
        applicationManagement: "Bewerbungs-Management",
        applicationPipeline: "Bewerbungs-Pipeline",
        otherStatus: "Sonstige:",

        // Crawl Status
        jobSearch: "Job-Suche",
        searchingForJobs: "Suche nach Jobs...",
        jobsFound: "Jobs gefunden",
        jobsSaved: "gespeichert",
        jobsSkipped: "übersprungen",
        processingJobDetails: "{count} von {total} Job Details werden verarbeitet",
        loadJobDetails: "Job Details laden",
        extractingDescriptions: "Extrahiere Stellenbeschreibungen...",
        aiExtraction: "KI-Extraktion",
        aiExtractionCount: "{count} von {total} extrahiert",
        analyzingCount: "{count} von {total} Jobs analysiert",
        allJobsAnalyzed: "Alle Jobs erfolgreich analysiert!",
        jobsRatedAndSaved: "{count} {jobs} wurden bewertet und gespeichert.",
        job: "Job wurde",
        jobs: "Jobs wurden",
        cancelCrawl: "Crawl abbrechen",
        cancelCrawlConfirm: "Möchten Sie diesen Crawl-Job wirklich abbrechen?",

        // Application Modal
        applicationPreview: "Anschreiben Vorschau",
        close: "Schließen",
        copyText: "Text kopieren",
        saveAsPdf: "Als PDF speichern",
        copiedToClipboard: "In die Zwischenablage kopiert!",
        downloadFailed: "Download fehlgeschlagen",
        pdfDownloadError: "Fehler beim PDF Download.",

        // Login
        systemAccess: "System-Zugang",
        identity: "Benutzername",
        secureKey: "Passwort",
        initializeSession: "Login",
        authFailed: "Authentifizierung fehlgeschlagen.",
        systemUnreachable: "System nicht erreichbar.",

        // Settings
        profileConfiguration: "Profil-Konfiguration",
        profileSubtitle: "Verwalte deine berufliche Identität und Sucheinstellungen",
        saveChanges: "Änderungen speichern",
        tryAgain: "Erneut versuchen",
        notifications: "Benachrichtigungen",
        generating: "Generiere...",
        updated: "Aktualisiert!",
        saving: "Speichert...",
        saved: "Gespeichert!",
        error: "Fehler",
        success: "Erfolg",
        analyzingPdf: "Analysiere PDF... (dauert 10-20s)",
        uploadFailed: "Upload fehlgeschlagen",
        importSuccess: "CV erfolgreich importiert!",
        importFailed: "Import fehlgeschlagen",
        targetParameters: "Ziel-Parameter",
        targetRole: "Ziel-Rolle",
        skillsComma: "Skills (Komma-getrennt)",
        minSalary: "Mindestgehalt",
        location: "Standort",
        preferencesNatural: "Präferenzen (Natürliche Sprache)",
        experience: "Erfahrung",
        keyProjects: "Wichtige Projekte",
        education: "Ausbildung",
        uploadCv: "Lebenslauf hochladen",
        dropPdf: "PDF ablegen, um Skills und Erfahrung automatisch zu extrahieren.",
        selectPdf: "PDF auswählen",
        analyzing: "Analysiere...",
        security: "Sicherheit",
        dangerZone: "Gefahrenzone",
        deleteAllJobs: "Alle Jobs löschen",
        deleteProfileOnly: "Nur Profil löschen",
        factoryReset: "Werkseinstellung (Alle Daten)",
        deleteJobsConfirm: "Sicher? Dies wird alle deine gecrawlten Jobs dauerhaft löschen.",
        deleteProfileConfirm: "Sicher? Dies wird dein Profil und deine CV-Daten dauerhaft löschen.",
        factoryResetConfirm: "WARNUNG: Dies wird ALLE Jobs und dein gesamtes Profil löschen. Alles. Sicher?",
        loadingProfile: "Profil wird geladen...",
        startingCrawler: "Crawler wird gestartet...",
        crawlJobsDispatched: "Crawl-Jobs versandt!",
        loading: "Wird geladen...",
        dayUnit: "T",
        hourUnit: "Std",
        minUnit: "Min",
        now: "jetzt",

        // Experience & Projects Fields
        company: "Firma",
        role: "Rolle",
        duration: "Zeitraum",
        description: "Beschreibung",
        projectName: "Projektname",
        techStack: "Tech Stack",

        // Admin
        adminControlPanel: "Admin-Kontrollzentrum",
        createNewUser: "Neuen Benutzer erstellen",
        username: "Benutzername",
        password: "Passwort",
        createUser: "Benutzer erstellen",
        id: "ID",
        clearance: "Freigabe",
        actions: "Aktionen",
        delete: "Löschen",
        areYouCertain: "Bist du sicher?",
        errorCreatingUser: "Fehler beim Erstellen des Benutzers",
        verifyingClearance: "Prüfe Berechtigung...",

        // Password Change
        currentPassword: "Aktuelles Passwort",
        newPassword: "Neues Passwort",
        updatePassword: "Passwort aktualisieren",
        updating: "Aktualisiere...",
        passwordUpdated: "Passwort aktualisiert!",
        networkError: "Netzwerkfehler",

        // Job Platforms
        jobPlatforms: "Job-Plattformen",
        platformsSubtitle: "URLs und automatisierte Scan-Intervalle verwalten",
        notificationsSubtitle: "Benachrichtigungsadapter konfigurieren",
        adding: "Füge hinzu...",
        platformAdded: "Plattform hinzugefügt!",
        crawlInProgress: "Crawl läuft...",
        scanNow: "Jetzt scannen",
        remove: "Entfernen",
        everyHour: "Jede Stunde",
        every6Hours: "Alle 6 Stunden",
        every12Hours: "Alle 12 Stunden",
        every24Hours: "Alle 24 Stunden",
        everyWeek: "Jede Woche",
        neverScanned: "Noch nie gescannt",
        lastScan: "Letzter Scan",
        lastScanned: "Zuletzt: {date}",
        addPlatformPlaceholder: "Neue Plattform-URL hinzufügen (z.B. LinkedIn, Indeed...)",
        invalidUrl: "Ungültiges URL-Format",
        invalidUrlProtocol: "URL muss mit http:// oder https:// beginnen",
        notificationsEnabled: "Benachrichtigungen aktiviert",
        notificationsDisabled: "Benachrichtigungen deaktiviert",
        platformActive: "Plattform aktiv",
        platformInactive: "Plattform inaktiv",
        deactivated: "Deaktiviert",

        // Filters
        all: "Alle",
        favorites: "Favoriten",
        noFavorites: "Keine Favoriten",
        confirm: "Bestätigen",
        cancel: "Abbrechen",

        // Missing keys from reports
        removePlatform: "Plattform entfernen",
        userCreated: "Benutzer erstellt!",
        deleteUser: "Benutzer löschen",

        // Dynamic List
        addItem: "Eintrag hinzufügen",
        noEntries: "Noch keine Einträge.",
        removeEntry: "Eintrag entfernen",
        completeProfileFirst: "Bitte vervollständige zuerst dein Profil.",

        // Job list filters
        filterSearchPlaceholder: "Nach Titel oder Unternehmen suchen...",
        allDomains: "Alle Domains",
        allPlatforms: "Alle Plattformen",
        allStatuses: "Alle Status",
        withApplication: "Mit Anschreiben",
        clearAllFilters: "Alle Filter löschen",

        // Deletion actions
        alsoDeleteListings: "Auch zugehörige Listings löschen",
        deleteAllFromPlatform: "Alle von dieser Plattform löschen",
        keepFavorites: "Favoriten behalten",
        keepApplications: "Listings mit Bewerbung behalten",
        select: "Auswählen",
        selected: "ausgewählt",
        selectAllVisible: "Alle sichtbaren auswählen",
        bulkDelete: "Ausgewählte löschen",
        deleteAllFromCompany: "Alle von {company} löschen",

        // Needs Attention / Follow-up / Prep
        needsAttention: "Bedarf Aufmerksamkeit",
        prepMaterialAvailable: "Prep Material",
        followUpDue: "Follow-up fällig",

        // Job Details Modal
        overview: "Übersicht",
        application: "Bewerbung",
        interviewPrep: "Interview Prep",
        companyProfile: "Firma",
        historyTab: "Verlauf",
        noApplication: "Noch keine Bewerbung generiert",
        jobDescription: "Stellenbeschreibung anzeigen",

        // Tab Labels
        status: "Status",
        documents: "Dokumente",
        shortInfo: "Info",
        shortApp: "App",
        shortInt: "Int",
        shortCo: "Firma",
        shortStatus: "Status",
        shortDocs: "Dok.",

        // Setup Warnings
        setupRequired: "Einrichtung erforderlich",
        profileIncomplete: "Profil unvollständig",
        noNotificationAdapter: "Keine Benachrichtigungen",
        completeProfileDesc: "Dein Profil ist noch nicht vollständig ausgefüllt. Ergänze es für bessere Match-Ergebnisse.",
        noNotificationAdapterDesc: "Du hast noch keine Benachrichtigungsdienste konfiguriert. Du wirst nicht über neue Jobs informiert.",
        actionCompleteProfile: "Profil vervollständigen",
        actionConfigureNotifications: "Benachrichtigungen einrichten",
        found: "gefunden",
        new: "neu",

        // Companies
        companies: "Firmen",
        companiesPageTitle: "Unternehmensprofile",
        companiesPageSubtitle: "Deep Intelligence zu allen Firmen in deiner Pipeline",

        // Language Preference
        languagePreference: "Spracheinstellung",

        // Profile Page
        profileAndResume: "Profil & Lebenslauf",
        profileCompletion: "Profil-Vollständigkeit",
        targetJob: "Ziel-Job",
        resume: "Lebenslauf",
        universityPlaceholder: "Universität, Abschluss...",

        // Settings - Notification Adapters
        deliveryMethods: "Zustellungs-Methoden",
        notificationAdapterInfo: "Konfiguriere hier deine Benachrichtigungs-Zugangsdaten. Die Aktivierung der Plattformen erfolgt individuell auf dem Dashboard.",
        active: "Aktiv",
        inactive: "Inaktiv",
        importantSecurityNote: "Wichtiger Sicherheitshinweis",
        gmailAppPasswordNote: "Verwende ausschließlich ein App-Passwort. Dein normales Google-Passwort wird aus Sicherheitsgründen abgelehnt.",
        createAppPassword: "App-Passwort erstellen",
        emailAddress: "Email Adresse",
        appPassword: "App Passwort",
        emailService: "Email Service",
        pushNotifications: "Push Notifications",
        pushoverKeysInfo: "Hol dir deine Keys auf Pushover.net",
        userKey: "User Key",
        apiToken: "API Token",
        notificationTemplates: "Benachrichtigungs-Vorlagen",
        customTemplates: "Eigene Vorlagen",

        // Archive
        archiveJob: "Job archivieren",
        archiveConfirm: "Möchten Sie diesen Job wirklich archivieren?",
        archiveSelected: "Ausgewählte archivieren",
        archiveAllFromCompany: "Alle von {company} archivieren",
        archiveEmpty: "Keine archivierten Jobs.",
        archivePageTitle: "Archiv",
        archivePageSubtitle: "Aus den Listings archivierte Jobs",

        // JobDocumentsTab
        notes: "Notizen",
        personalNotesPlaceholder: "Notizen zur Stelle, Gesprächsnotizen, persönliche Eindrücke...",
        savingNotes: "Speichern...",
        notesSaved: "Gespeichert",
        tasks: "Aufgaben",
        noTasks: "Keine Aufgaben – füge eine hinzu.",
        newTask: "Neue Aufgabe...",
        files: "Dateien",
        fileLimitInfo: "PDF, DOCX, Bild – max. 10 MB",
        uploading: "Wird hochgeladen...",
        dropFileHere: "Datei hier ablegen oder klicken",
        loadingFile: "Laden...",
        clickToOpen: "Klicken zum Öffnen",
        noFiles: "Noch keine Dateien hochgeladen",
        viewFile: "Anzeigen",
        downloadFile: "Herunterladen",
        maxFileSize: "Maximale Dateigröße 10 MB",
        uploadFailed: "Upload fehlgeschlagen",
        genericError: "Ein Fehler ist aufgetreten",

        // Guidance
        guidanceWhatNow: "Was jetzt?",
        guidanceOpenNext: "Prüfe den Job und entscheide, ob du dich bewerben willst.",
        guidanceOpenItem1: "KI-Analyse lesen (Übersicht-Tab)",
        guidanceOpenItem2: "Stellenbeschreibung vollständig lesen",
        guidanceOpenItem3: "Kurze Recherche zum Unternehmen",
        guidanceOpenItem4: "Bewerbungsentwurf starten",
        guidanceOpenNudge: "Jeder Prozess beginnt mit einer ehrlichen Selbsteinschätzung.",

        guidanceDraftedNext: "Überprüfe deinen Bewerbungsentwurf und sende ihn ab.",
        guidanceDraftedItem1: "Bewerbungsentwurf generiert",
        guidanceDraftedItem2: "Entwurf auf Vollständigkeit und Tonfall prüfen",
        guidanceDraftedItem3: "Anschreiben personalisieren (Name, Job-Referenz)",
        guidanceDraftedItem4: "Unterlagen versenden / Formular ausfüllen",
        guidanceDraftedNudge: "Perfekt ist der Feind von gut — jetzt abschicken.",

        guidanceAppliedNext: "Dokumentiere deine Bewerbung und plane dein Follow-up.",
        guidanceAppliedItem1: "Bewerbungsbestätigung erhalten oder geprüft",
        guidanceAppliedItem2: "Follow-up Datum gesetzt",
        guidanceAppliedItem3: "Interview-Vorbereitung erstellt",
        guidanceAppliedItem4: "Geduld: Feedback-Dauer oft 2–4 Wochen",
        guidanceAppliedNudge: "Du hast dich beworben — das war der schwerste Schritt.",

        guidanceInterviewNext: "Bereite dich intensiv auf das Vorstellungsgespräch vor.",
        guidanceInterviewItem1: "Interview-Vorbereitungsmaterial generiert",
        guidanceInterviewItem2: "3 eigene Stärken-Beispiele (STAR-Methode) vorbereitet",
        guidanceInterviewItem3: "Fragen an das Unternehmen vorbereitet",
        guidanceInterviewItem4: "Logistik geklärt (Ort, Zeit, Kontakt, Video-Link)",
        guidanceInterviewNudge: "Vorbereitung ist der Unterschied zwischen Glück und Können.",

        guidanceOfferNext: "Analysiere das Angebot sorgfältig, bevor du antwortest.",
        guidanceOfferItem1: "Konditionen prüfen (Gehalt, Urlaub, Remote-Anteil)",
        guidanceOfferItem2: "Gehalts-Benchmark verglichen",
        guidanceOfferItem3: "Verhandlungsspielraum identifiziert",
        guidanceOfferItem4: "48h Bedenkzeit nehmen (professionell & üblich)",
        guidanceOfferNudge: "Ein Angebot ist eine Einladung zum Gespräch, kein Ultimatum.",

        guidanceAcceptedNext: "Glückwunsch! Bereite deinen Start vor.",
        guidanceAcceptedItem1: "Schriftlicher Vertrag erhalten und geprüft",
        guidanceAcceptedItem2: "Starttermin und Onboarding-Infos bestätigt",
        guidanceAcceptedItem3: "Höfliche Absage an alle anderen Bewerbungen",
        guidanceAcceptedItem4: "Offene Positionen hier archiviert",
        guidanceAcceptedNudge: "Du hast es geschafft. Jetzt beginnt das nächste Kapitel.",

        guidanceRejectedNext: "Hol dir Feedback und ziehe Lehren aus dem Prozess.",
        guidanceRejectedItem1: "Absageschreiben sorgfältig lesen",
        guidanceRejectedItem2: "Feedback anfordern (bei persönlichen Kontakten)",
        guidanceRejectedItem3: "Bewerbungsunterlagen für die nächste Runde angepasst",
        guidanceRejectedItem4: "Nächste passende Position identifizieren",
        guidanceRejectedNudge: "Eine Absage zeigt dir, welche Tür besser passt.",

        guidanceFailedNext: "Prüfe, ob ein technisches Problem vorliegt und starte erneut.",
        guidanceFailedItem1: "Fehlermeldung in der Übersicht lesen",
        guidanceFailedItem2: "Bewerbungsentwurf manuell prüfen",
        guidanceFailedItem3: "Regenerierung versucht",
        guidanceFailedItem4: "Support kontaktieren, wenn das Problem bestehen bleibt",
        guidanceFailedNudge: "Manchmal hakt es technisch — kein Rückschlag, sondern ein Hinweis.",
    }
};

export type TranslationKey = keyof typeof translations.en;
