"""Add notes field

Revision ID: 9e3f38fb631b
Revises: 2b8377219f40
Create Date: 2026-03-08 17:51:59.553415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e3f38fb631b'
down_revision: Union[str, Sequence[str], None] = '2b8377219f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('users', 'token_version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'token_version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_column('jobs', 'notes')
    # ### end Alembic commands ###
